# Generated by Django 3.0 on 2019-12-28 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20191227_1813'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='account',
            order_with_respect_to='date_created',
        ),
    ]
