# Generated by Django 3.0 on 2019-12-28 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20191228_0929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['accountid']},
        ),
        migrations.AlterModelTable(
            name='account',
            table='accounts',
        ),
        migrations.AlterOrderWithRespectTo(
            name='account',
            order_with_respect_to=None,
        ),
    ]
