# Generated by Django 3.0 on 2019-12-29 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_yard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yard',
            old_name='accountid',
            new_name='account',
        ),
    ]
