# Generated by Django 3.0 on 2019-12-29 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20191228_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yard',
            name='mow_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
    ]
