# Generated by Django 3.0 on 2019-12-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20191228_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yard',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
