# Generated by Django 3.0 on 2019-12-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20191228_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yard',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='yard',
            name='mow_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
    ]
