# Generated by Django 3.0 on 2019-12-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20191228_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yard',
            name='mow_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
