# Generated by Django 3.0.1 on 2019-12-30 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20191230_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='zip_code',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='yard',
            name='zip_code',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
    ]
