# Generated by Django 3.0.1 on 2019-12-31 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20191230_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('job_typeid', models.AutoField(primary_key=True, serialize=False)),
                ('job_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'job_types',
                'ordering': ['job_typeid'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('jobid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_completed', models.DateTimeField(blank=True)),
                ('job_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billed', models.BooleanField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.JobType')),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['jobid'],
            },
        ),
    ]
